server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka/
      
security:
  oauth2:
    resource:
      filter-order: 3

logging:
  level:
    org.springframework.security: DEBUG
    
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oauth?useSSL=false
    username: oauth
    password: 
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    database: 0