server:
  port: 8061
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    org:
      springframework:
         security: DEBUG  
    
spring:
   data:
     mongodb:
        url: "mongodb://letsgo:letsgo@localhost:27017/letsgo"
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka/
      
security:
  oauth2:
    resource:
      id: organization-service
      user-info-uri: http://localhost:8060/ua/user
      prefer-token-info: false      